# Generated by Django 2.1 on 2018-10-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='domain_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='schema_name',
        ),
    ]
