# Generated by Django 2.1 on 2018-10-07 03:51

import contests.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('banner', models.ImageField(blank=True, upload_to='contests/banner')),
                ('start_date', models.DateField(help_text='Please use the following format: YYYY-MM-DD HH:MM:ss. e.g, 2018-08-14 22:10:24.', validators=[contests.models.validate_star_date])),
                ('end_date', models.DateField()),
                ('award_description', models.TextField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contests/videos')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Converted', 'Converted')], default='Processing', max_length=20)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Participant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
